package com.example.meditronix;

public class GenericDrugsList {
    static String[] genericDrugNames = {
            "alendronate tablet",
            "acyclovir capsule",
            "acyclovir tablet",
            "albuterol inhalation solution",
            "albuterol sulfate",
            "alclometasone dipropionate cream",
            "alfuzosin hcl",
            "alitretinoin",
            "allopurinol tablet",
            "alprazolam",
            "altretamine",
            "amiodarone tablet",
            "amitriptyline tablet",
            "amlodipine and valsartan",
            "amlodipine besylate",
            "amlodipine, valsartan, hydrochlorothiazide",
            "Amlodipine/Benazepril capsule",
            "amoxapine tablet",
            "anastrazole",
            "antihypertensive combinations",
            "antihistamine",
            "artificial tears 1.4% drops (OTC)",
            "aspirin EC tablet (OTC)",
            "atenolol tablet",
            "atenolol/chlorthalidone tablet",
            "atorvastatin calcium",
            "augmented betamethasone dipropionate",
            "azathioprine",
            "azelastine",
            "Azelastine nasal spray",
            "baclofen tablet",
            "Belladonna Alkaloids with Phenobarbital",
            "benazepril HCTZ tablet",
            "benazepril tablet",
            "benzonatate",
            "benzonatate capsule",
            "benztropine tablet",
            "bethanechol tablet",
            "bicalutamide",
            "bisoprolol/HCTZ tablet",
            "brimonidine tartrate",
            "bromocriptine tablet",
            "budesonide inhalation suspension",
            "bupropion hcl",
            "bupropion HCL tablet",
            "buspirone tablet",
            "Calcitonin-salmon (rDNA origin)",
            "calcitriol capsule",
            "calcium acetate",
            "candesartan cilexetil-hydrochlorothiazide",
            "candesartan cilextil",
            "capsaicin cream, 0.035% (OTC)",
            "captopril tablet",
            "carbamazepine tablet",
            "carbidopa/levo SR tablet",
            "carbidopa/levo tablet",
            "carvedilol",
            "cetirizine HCl tablet - OTC",
            "cevimeline HCl",
            "chlordiazepoxide capsule",
            "chlorpromazine HCL",
            "chlorthalidone tablet",
            "cholestyramine",
            "cilostazol tablet",
            "citalopram tablet",
            "clindamycin phosphate",
            "clomipramine hcl",
            "clonazepam tablet",
            "clonidine HCL tablets",
            "clonidine patch",
            "clopidogrel bisulfate tablets",
            "clotrimazole/betamethasone cream",
            "colestipol hcl",
            "decitabine",
            "Dexmethylphenidate HCl tablet",
            "dextroamphetamine sulfate ER capsule",
            "dextroamphetamine-amphetamine ER capsule",
            "dextroamphetamine-amphetamine tablet",
            "diazepam tablet",
            "diclofenac EC tablet",
            "diclofenac ER tablet",
            "dicyclomine capsule",
            "dicyclomine tablet",
            "digoxin tablets",
            "diltiazem ER capsule",
            "diltiazem hcl cd",
            "diphenoxylate hydrochloride/atropine sulfate",
            "diphenoxylate/atropine tablet",
            "Divalproex DR tablet",
            "donepezil HCI",
            "dorzolamide HCL",
            "doxazosin mesylate",
            "doxepin capsule",
            "enalapril maleate tablet",
            "enalapril maleate-hydrochlorothiazide tablets",
            "epinephrine auto injector",
            "eplerenone tablet",
            "escitalopram oxalate",
            "esomeprazole DR capsule",
            "estradiol tablet",
            "estropipate tablet",
            "eszopiclone",
            "etodolac capsule",
            "etodolac tablet",
            "famotidine tablet",
            "felodipine ER tablet",
            "fenofibrate",
            "fenofibrate, micronized capsule",
            "fenofibric acid DR capsule",
            "ferrous sulfate EC tablet",
            "finasteride tablet",
            "flecainide acetate tablet",
            "fluconazole",
            "fluoxetine capsule",
            "fluticasone nasal spray (50 mcg)",
            "fluvoxamine maleate tablet",
            "folic acid 2.2 tablet",
            "folic acid tablet",
            "furosemide tablet",
            "gabapentin",
            "gemfibrozil",
            "glimepiride",
            "glipizide",
            "glipizide extended release",
            "glyburide tablet",
            "glyburide/Metformin tablet",
            "guanfacine",
            "halobetasol prop ointment, 0.05%",
            "haloperidol tablet",
            "hydralazine tablet",
            "hydrochlorothiazide capsule",
            "hydrochlorothiazide tablet",
            "hydrocortisone tablet",
            "hydroxychloroquine tablet",
            "hydroxyurea capsule",
            "hydroxyzine HCL tablet",
            "hydroxyzine pamoate",
            "ibuprofen tablet",
            "indapamide tablet",
            "Ipratropium/Albuterol Inhalation Solution",
            "irbesartan",
            "irbesartan-hydrochlorothiazide",
            "isoniazid tablet",
            "isosorbide mononitrate",
            "isosorbide mononitrate (10mg,20mg)",
            "ketotifen fumerate OTC solution",
            "labetalol HCL tablet",
            "lactulose oral solution",
            "lamotrigine",
            "lansoprazole DR capsule",
            "latanoprost solution",
            "letrozole",
            "levalbuterol hcl",
            "levetiracetam ER",
            "levetiracetam tablet",
            "levocetirizine dihydrochloride",
            "levothyroxine",
            "lidocaine 2% viscous solution",
            "lidocaine patch 5%",
            "liothyronine sodium",
            "lisinopril tablet",
            "lisinopril/HCTZ tablet",
            "Lithium Carbonate capsule",
            "loperamide capsule",
            "loratadine OTC tablet",
            "lorazepam tablet",
            "losartan potassium",
            "lovastatin tablet",
            "loxapine capsule",
            "magnesium oxide tablet (OTC)",
            "meclizine HCI",
            "medroxyprogesterone acetate",
            "meloxicam",
            "memantine hcl",
            "metformin",
            "metformin hcl, extended release",
            "methimazole tablets",
            "methocarbamol tablet",
            "methotrexate",
            "methylphenidate CD capsule",
            "methylphenidate hcl",
            "methylphenidate tablet",
            "metoclopramide HCL tablet",
            "metolazone tablet",
            "metoprolol succinate/hctz",
            "metoprolol tartrate tablet",
            "micronized glyburide",
            "midodrine HCl tablet",
            "minocycline capsule",
            "minocycline HCL capsule",
            "mirtazapine tablet",
            "mometasone furoate",
            "montelukast sodium",
            "mycophenolate mofetil",
            "nabumetone tablet",
            "naproxen sodium tablet",
            "naproxen tablet",
            "niacin",
            "niacin extented-release tablets",
            "niacin SA capsule (OTC)",
            "nifedipine capsule",
            "nifedipine CR tablet",
            "nilutamide",
            "nitroglycerin SA capsule",
            "norethindrone tablet",
            "norethindrone/ethinyl estradiol tablet",
            "nortriptyline HCL capsule",
            "nyamyc topical powder",
            "nystatin tablet",
            "olanzapine",
            "omega-3-acid ethyl esters",
            "omeprazole capsule",
            "ondansetron ODT tablet",
            "ondansetron tablet",
            "oxandrolone tablet",
            "oxybutynin tablet",
            "pantoprazole sodium",
            "paroxetine HCL tablet",
            "pentoxifylline ER tablet",
            "perphenazine tablet",
            "Phenobarbital, Hyoscyamine Sulfate, Atropine Sulfate, Scopolamine Hydrobromide",
            "phenytoin sodium capsule",
            "pilocarpine",
            "pioglitazone hydrochloride",
            "PNV Prenatal Multivitamin Plus Iron",
            "potassium chloride ER tablet",
            "potassium Iodide",
            "pramipexole dihydrochloride tablets",
            "pravastatin tablet",
            "prazosin capsule",
            "prednisone tablet",
            "primidone",
            "prochlorperazine tablet",
            "progesterone capsule",
            "propafenone hydrochloride",
            "propranolol HCL ER",
            "propranolol tablet",
            "propylthiouracil tablet",
            "pyridostigmine bromide",
            "quetiapine fumarate",
            "quinapril HCI",
            "quinapril/HCTZ tablet",
            "rabeprazole sodium",
            "raloxifene tablet",
            "ramipril capsule",
            "ranitidine tablet",
            "repaglinide tablet",
            "rifampin capsule",
            "risedronate sodium tablet",
            "risperidone tablet",
            "rivastigmine tartrate capsule",
            "rosuvastatin calcium",
            "sertraline hcl tablet",
            "sildenafil tablet",
            "simvastatin tablet",
            "sitagliptin phosphate",
            "solifenacin succinate",
            "spironolactone tablet",
            "sulfamethoxazole and trimethoprim tablet",
            "sulindac tablet",
            "sumatriptan succinate",
            "tadalafil tablet",
            "tamsulosin hcl capsule",
            "temazepam capsule",
            "terazosin hcl capsule",
            "terbinafine hcl tablet",
            "testosterone gel",
            "thyroid desiccated",
            "timolol maleate",
            "tizanidine tablet",
            "tolterodine tartrate",
            "topiramate tablet",
            "torsemide tablet",
            "tramadol hcl tablet",
            "trazodone tablet",
            "triamcinolone acetonide cream",
            "triamcinolone acetonide nasal spray",
            "triamcinolone acetonide ointment",
            "triamterene and hydrochlorothiazide capsule",
            "triamterene and hydrochlorothiazide tablet",
            "triazolam tablet",
            "valsartan tablet",
            "valsartan and hydrochlorothiazide",
            "venlafaxine tablet",
            "verapamil tablet",
            "warfarin sodium tablet",
            "zolpidem tartrate tablet"
    };

    static String[] dosageUnits = {
            "",          // Blank for no units
            // Solid Tablets and Capsules
            "mg",        // Milligram
            "g",         // Gram
            "mcg",       // Microgram
            "U",         // Unit
            "IU",        // International Unit
            "mEq",       // Milliequivalent
            "tablet",    // Tablet
            "caplet",    // Caplet
            "capsule",   // Capsule

            // Liquids
            "mL",        // Milliliter
            "tsp",       // Teaspoon
            "tbsp",      // Tablespoon
            "gtt",       // Drop
            "mcg/mL",    // Microgram per milliliter
            "mg/mL",     // Milligram per milliliter
            "g/mL",      // Gram per milliliter
            "mEq/mL",    // Milliequivalent per milliliter
            "% w/v",     // Percentage solution (weight/volume)
            "% v/v",     // Percentage solution (volume/volume)
            "IU/mL",     // International Unit per milliliter
            "dose"       // Per Dose Volume
    }
    ;


}
